# Test von Powershell im Runner
name: PowershellHelloWorld

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    # runs-on: windows-latest
    runs-on: ubuntu-latest
    
    steps:
      - name: Upgrade to latest powershell on Linux
        run: |
          # Download the powershell '.tar.gz' archive
          curl -L -o /tmp/powershell.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v7.4.0/powershell-7.4.0-linux-x64.tar.gz
          # Create the target folder where powershell will be placed
          sudo mkdir -p /opt/microsoft/powershell/7
          # Expand powershell to the target folder
          sudo tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7
          # Set execute permissions
          sudo chmod +x /opt/microsoft/powershell/7/pwsh
          # Create the symbolic link that points to pwsh
          sudo ln -s /opt/microsoft/powershell/7/pwsh /usr/bin/pwsh

#      - name: Upgrade to latest powershell on Windows
#        run: |
#          Invoke-Expression "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI -quiet"
#          "C:\Program Files\PowerShell\7" >> $env:GITHUB_PATH
#        shell: powershell
        
      - name: TestPowershell
        run: |
         Write-Host "Hallo Welt!"
         $PSVersionTable
         
