# Test von Powershell im Runner
name: PowershellHelloWorld

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Upgrade to latest powershell
        run: |
          Invoke-Expression "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI -quiet"
          "C:\Program Files\PowerShell\7" >> $env:GITHUB_PATH
        
      - name: TestPowershell
        run: |
         Write-Host "Hallo Welt!"
         $PSVersionTable
         
