# Test von Powershell im Runner
name: PowershellHelloWorld

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: TestPowershell
      run: |
         Write-Host "Hallo Welt!"
         $PSVersionTable
         
